openapi: 3.0.0
info:
  title: MatchBot API
  description: Microservice providing donation matching and related APIs
  version: 1.0.0
  contact:
    name: The Big Give
    url: https://www.thebiggive.org.uk
    email: tech@thebiggive.org.uk
  license:
    name: MIT
    url: https://github.com/thebiggive/matchbot/blob/main/LICENSE
servers:
  - url: https://matchbot.thebiggive.org.uk
    description: Production server
  - url: https://matchbot-staging.thebiggive.org.uk
    description: Staging server
paths:
  # This section will be merged with paths from PHP annotations
tags:
  - name: donations
    description: Donation operations
  - name: campaigns
    description: Campaign operations
  - name: charities
    description: Charity operations
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
