#!/usr/bin/env php
<?php

declare(strict_types=1);

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Tools\Console\ConsoleRunner;
use Doctrine\ORM\Tools\Console\EntityManagerProvider\SingleManagerProvider;
use Doctrine\Migrations\Configuration\EntityManager\ExistingEntityManager;
use Doctrine\Migrations\Configuration\Migration\PhpFile;
use Doctrine\Migrations\DependencyFactory;
use Doctrine\Migrations\Tools\Console\Command;

$psr11App = require __DIR__ . '/bootstrap.php';

$entityManager = $psr11App->get(EntityManagerInterface::class);

$commands = [];

if (class_exists(DependencyFactory::class)) {
    $migrationConfig = new PhpFile(__DIR__ . '/migrations.php');
    $dependencyFactory = DependencyFactory::fromEntityManager($migrationConfig, new ExistingEntityManager($entityManager));

    $commands = [
        new Command\CurrentCommand($dependencyFactory),
        new Command\DiffCommand($dependencyFactory),
        new Command\DumpSchemaCommand($dependencyFactory),
        new Command\ExecuteCommand($dependencyFactory),
        new Command\GenerateCommand($dependencyFactory),
        new Command\LatestCommand($dependencyFactory),
        new Command\ListCommand($dependencyFactory),
        new Command\MigrateCommand($dependencyFactory),
        new Command\RollupCommand($dependencyFactory),
        new Command\StatusCommand($dependencyFactory),
        new Command\SyncMetadataCommand($dependencyFactory),
        new Command\UpToDateCommand($dependencyFactory),
        new Command\VersionCommand($dependencyFactory),
    ];
}

ConsoleRunner::run(
    helperSetOrProvider: new SingleManagerProvider($entityManager),
    commands: $commands
);
