version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@9.0.2
  aws-ecs: circleci/aws-ecs@3.2.0
  aws-cli: circleci/aws-cli@4.1.3
  jira: circleci/jira@1.3.1
  slack: circleci/slack@4.12.1

jobs:
  test: # Also lints first
    # Working directory must match docker-compose mount / Docker `COPY` for real Doctrine proxy
    # generation-dependent tests to work.
    working_directory: /var/www/html
    resource_class: large
    docker:
      - image: thebiggive/php:dev-8.3
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_SCHEMA: matchbot
          MYSQL_USER: root
          MYSQL_PASSWORD: tbgCircle123

          REDIS_HOST: 127.0.0.1
      - image: cimg/mysql:8.0
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN
        environment:
          MYSQL_DATABASE: matchbot
          MYSQL_ROOT_PASSWORD: tbgCircle123
      - image: redis:7.0
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN

    steps:
      - checkout

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}

      - run: composer install --no-interaction

      - run: composer check-platform-reqs

      - save_cache:
          paths:
            - vendor
          key: composer-v1-{{ checksum "composer.lock" }}

      - run: composer run lint:check

      - run: composer run sa:check

      - run: composer run test

      - run: vendor/bin/doctrine-migrations migrate --no-interaction --allow-no-migration --verbose

      - run: composer run integration-test

      - run: vendor/bin/doctrine-migrations diff --allow-empty-diff # check that this works

      - store_test_results:
          path: reports/unit-test.xml

      - store_artifacts:
          path: reports

  mutation_coverage:
    resource_class: large
    working_directory: /var/www/html
    docker:
      - image: thebiggive/php:dev-8.3
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN
        environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_SCHEMA: matchbot
          MYSQL_USER: root
          MYSQL_PASSWORD: tbgCircle123

          REDIS_HOST: 127.0.0.1
      - image: cimg/mysql:8.0
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN
        environment:
          MYSQL_DATABASE: matchbot
          MYSQL_ROOT_PASSWORD: tbgCircle123
      - image: redis:7.0
        auth:
          username: $DOCKER_HUB_USERNAME
          password: $DOCKER_HUB_ACCESS_TOKEN

    steps:
      - checkout

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}

      - run: composer install --no-interaction

      - save_cache:
          paths:
            - vendor
          key: composer-v1-{{ checksum "composer.lock" }}

      - run:
          name: Mutation Test only changed and added files in PR
          command: |
            vendor/bin/infection --git-diff-filter=AM --git-diff-base=develop || true # there may be no changed covered PHP files.
            mv reports/mutation-testing reports/mutation-testing-changed-files || true # in which case the mv would also fail but we don't care.

      - run:
          name: Mutation Test all files
          command: |
            composer run mutation-test
            mv reports/mutation-testing reports/mutation-testing-all-files

      - store_artifacts:
          path: reports
workflows:
  build:
    jobs:
      - test:
          context:
            - docker-hub-creds
            - jira
            - slack
          post-steps:
            - jira/notify:
                job_type: build
                environment_type: development
            - slack/notify:
                event: fail
                template: basic_fail_1
      - mutation_coverage:
          context:
            - docker-hub-creds
          requires:
            - test

  deploy-regression:
    jobs:
      - test:
          filters:
            branches:
              only:
                - develop
          context:
            - docker-hub-creds
      - aws-ecr/build_and_push_image:
          account_id: ${AWS_ECR_REGISTRY_ID}
          region: '${AWS_REGION}'
          context:
            - ecs-deploys
          requires:
            - test
          repo: '${AWS_ECR_REPO_NAME}'
          tag: 'regression,regression-${CIRCLE_SHA1}'
          auth:
            - aws-cli/setup:
                aws_access_key_id: AWS_ACCESS_KEY_ID
                aws_secret_access_key: AWS_SECRET_ACCESS_KEY
      - aws-ecs/deploy-service-update:
          context:
            - ecs-deploys
            - jira
            - slack
          requires:
            - aws-ecr/build_and_push_image
          family: 'tbg-regression-${AWS_REGION}-${AWS_ECS_SERVICE_SUFFIX_WEB}'
          cluster: 'tbg-regression-${AWS_REGION}'
          container-image-name-updates: 'container=matchbot_web,tag=regression-${CIRCLE_SHA1}'
          post-steps:
            - jira/notify:
                job_type: deployment
            - slack/notify:
                custom: |
                  {
                    "blocks": [
                      {
                        "type": "section",
                        "fields": [
                          {
                            "type": "mrkdwn",
                            "text": "*Regression: Matchbot deployed!* All visitors should see the updated app version within 30 minutes."
                          }
                        ]
                      }
                    ]
                  }
            - slack/notify:
                event: fail
                template: basic_fail_1

  deploy-staging:
    jobs:
      - test:
          filters:
            branches:
              only:
                - develop
          context:
            - docker-hub-creds
      - aws-ecr/build_and_push_image:
          account_id: ${AWS_ECR_REGISTRY_ID}
          region: '${AWS_REGION}'
          context:
            - ecs-deploys
          requires:
            - test
          repo: '${AWS_ECR_REPO_NAME}'
          tag: 'staging,staging-${CIRCLE_SHA1}'
          auth:
            - aws-cli/setup:
                aws_access_key_id: AWS_ACCESS_KEY_ID
                aws_secret_access_key: AWS_SECRET_ACCESS_KEY
      - aws-ecs/deploy-service-update:
          context:
            - ecs-deploys
            - jira
            - slack
          requires:
            - aws-ecr/build_and_push_image
          family: 'tbg-staging-${AWS_REGION}-${AWS_ECS_SERVICE_SUFFIX_WEB}'
          cluster: 'tbg-staging-${AWS_REGION}'
          container-image-name-updates: 'container=matchbot_web,tag=staging-${CIRCLE_SHA1}'
          post-steps:
            - slack/notify:
                event: fail
                template: basic_fail_1
            - jira/notify:
                job_type: deployment
                environment_type: staging
            - slack/notify:
                custom: |
                  {
                    "blocks": [
                      {
                        "type": "section",
                        "fields": [
                          {
                            "type": "mrkdwn",
                            "text": "*Staging: Matchbot deployed!* All visitors should see the updated app version within 30 minutes."
                          }
                        ]
                      }
                    ]
                  }

  deploy-production:
    jobs:
      - test:
          filters:
            branches:
              only:
                - main
          context:
            - docker-hub-creds
      - aws-ecr/build_and_push_image:
          account_id: ${AWS_ECR_REGISTRY_ID}
          context:
            - ecs-deploys
          requires:
            - test
          repo: '${AWS_ECR_REPO_NAME}'
          tag: 'production,production-${CIRCLE_SHA1}'
          region: '${AWS_REGION}'
          auth:
            - aws-cli/setup:
                aws_access_key_id: AWS_ACCESS_KEY_ID
                aws_secret_access_key: AWS_SECRET_ACCESS_KEY
      - aws-ecs/deploy-service-update:
          context:
            - ecs-deploys
            - jira
            - slack
          requires:
            - aws-ecr/build_and_push_image
          family: 'tbg-production-${AWS_REGION}-${AWS_ECS_SERVICE_SUFFIX_WEB}'
          cluster: 'tbg-production-${AWS_REGION}'
          container-image-name-updates: 'container=matchbot_web,tag=production-${CIRCLE_SHA1}'
          post-steps:
            - slack/notify:
                event: fail
                template: basic_fail_1
            - jira/notify:
                job_type: deployment
                environment_type: production
            - slack/notify:
                custom: |
                  {
                    "blocks": [
                      {
                        "type": "section",
                        "fields": [
                          {
                            "type": "mrkdwn",
                            "text": "*Production: Matchbot deployed!* All visitors should see the updated app version within 30 minutes."
                          }
                        ]
                      }
                    ]
                  }
