version: 2.1

orbs:
  jira: circleci/jira@1.0.6
  slack: circleci/slack@3.4.0

jobs:
  test: # Also lints first
    docker:
      - image: circleci/php:7.3

    steps:
      - checkout

      - run: sudo docker-php-ext-install bcmath pdo_mysql

      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}

      - run: composer install --no-interaction

      - save_cache:
          paths:
            - vendor
          key: composer-v1-{{ checksum "composer.lock" }}

      - run: composer run lint:check

      - run: composer run test

workflows:
  build:
    jobs:
      - test:
          post-steps:
            - jira/notify:
                job_type: build
                environment_type: development
            - slack/notify-on-failure: ~
