-- Auto generated file, do not edit.
-- run ./matchbot matchbot:write-schema-files to update

-- Note that CHARSET and COLLATE details have been removed to allow sucessful comparisons between schemas
-- on dev machines and CircleCI. Do not use these files to create a database. They are provided for
-- information only.

CREATE TABLE `Donation` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `campaign_id` int unsigned NOT NULL,
  `uuid` char(36) NOT NULL COMMENT '(DC2Type:uuid)',
  `transactionId` varchar(255) DEFAULT NULL,
  `amount` decimal(18,2) NOT NULL,
  `donationStatus` varchar(255) NOT NULL,
  `charityComms` tinyint(1) DEFAULT NULL,
  `giftAid` tinyint(1) NOT NULL,
  `tbgComms` tinyint(1) DEFAULT NULL,
  `donorCountryCode` varchar(2) DEFAULT NULL,
  `donorEmailAddress` varchar(255) DEFAULT NULL,
  `donorFirstName` varchar(255) DEFAULT NULL,
  `donorLastName` varchar(255) DEFAULT NULL,
  `donorPostalAddress` varchar(255) DEFAULT NULL,
  `salesforceLastPush` datetime DEFAULT NULL,
  `salesforcePushStatus` varchar(255) NOT NULL,
  `salesforceId` varchar(18) DEFAULT NULL,
  `createdAt` datetime NOT NULL,
  `updatedAt` datetime NOT NULL,
  `tipAmount` decimal(18,2) NOT NULL,
  `psp` varchar(20) NOT NULL,
  `donorHomeAddressLine1` varchar(255) DEFAULT NULL,
  `donorHomePostcode` varchar(255) DEFAULT NULL,
  `tipGiftAid` tinyint(1) DEFAULT NULL,
  `chargeId` varchar(255) DEFAULT NULL,
  `championComms` tinyint(1) DEFAULT NULL,
  `charityFee` decimal(18,2) NOT NULL,
  `charityFeeVat` decimal(18,2) NOT NULL,
  `originalPspFee` decimal(18,2) NOT NULL,
  `currencyCode` varchar(3) NOT NULL,
  `collectedAt` datetime DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)',
  `refundedAt` datetime DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)',
  `tbgShouldProcessGiftAid` tinyint(1) DEFAULT NULL,
  `tbgGiftAidRequestQueuedAt` datetime DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)',
  `tbgGiftAidRequestFailedAt` datetime DEFAULT NULL,
  `transferId` varchar(255) DEFAULT NULL,
  `tbgGiftAidRequestConfirmedCompleteAt` datetime DEFAULT NULL,
  `tbgGiftAidRequestCorrelationId` varchar(255) DEFAULT NULL,
  `tbgGiftAidResponseDetail` text,
  `pspCustomerId` varchar(255) DEFAULT NULL,
  `paymentMethodType` varchar(255) DEFAULT NULL,
  `totalPaidByDonor` decimal(18,2) DEFAULT NULL,
  `preAuthorizationDate` datetime DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)',
  `mandate_id` int unsigned DEFAULT NULL,
  `mandateSequenceNumber` int DEFAULT NULL,
  `tipRefundAmount` decimal(18,2) DEFAULT NULL,
  `giftAidRemovedAt` datetime DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)',
  `donorUUID` char(36) DEFAULT NULL COMMENT '(DC2Type:uuid)',
  `stripePayoutId` varchar(255) DEFAULT NULL,
  `paidOutAt` datetime DEFAULT NULL COMMENT '(DC2Type:datetime_immutable)',
  `payoutSuccessful` tinyint(1) DEFAULT NULL,
  `paymentCard_brand` varchar(255) DEFAULT NULL,
  `paymentCard_country` varchar(255) DEFAULT NULL,
  `expectedMatchAmount_amountInPence` int NOT NULL,
  `expectedMatchAmount_currency` varchar(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UNIQ_C893E3F6D17F50A6` (`uuid`),
  UNIQUE KEY `UNIQ_C893E3F6C2F43114` (`transactionId`),
  UNIQUE KEY `UNIQ_C893E3F6D8961D21` (`salesforceId`),
  UNIQUE KEY `UNIQ_C893E3F6402C829F` (`chargeId`),
  UNIQUE KEY `UNIQ_C893E3F6AE9826DA` (`transferId`),
  UNIQUE KEY `UNIQ_C893E3F621F7BD156C1129CD` (`mandateSequenceNumber`,`mandate_id`),
  KEY `IDX_C893E3F6F639F774` (`campaign_id`),
  KEY `date_and_status` (`createdAt`,`donationStatus`),
  KEY `salesforcePushStatus` (`salesforcePushStatus`),
  KEY `campaign_and_status` (`campaign_id`,`donationStatus`),
  KEY `updated_date_and_status` (`updatedAt`,`donationStatus`),
  KEY `pspCustomerId` (`pspCustomerId`),
  KEY `IDX_C893E3F66C1129CD` (`mandate_id`),
  CONSTRAINT `FK_C893E3F66C1129CD` FOREIGN KEY (`mandate_id`) REFERENCES `RegularGivingMandate` (`id`),
  CONSTRAINT `FK_C893E3F6F639F774` FOREIGN KEY (`campaign_id`) REFERENCES `Campaign` (`id`)
)
