<?php

declare(strict_types=1);

namespace MatchBot\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * DO NOT MERGE!!!!!!!!!!!
 *
 * This seems to be wrong - we need a full date and time, not just a date. It was auto generated by the ORM following
 * the upgrade, so I want to keep it on the branch for now to see if we can get closer to green to see what's going
 * wrong.
 */
final class Version20260311181441 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Change campaign date fields as part of Doctrine 3 Upgrade';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE Campaign CHANGE startDate startDate DATE NOT NULL, CHANGE endDate endDate DATE NOT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE Campaign CHANGE startDate startDate DATETIME NOT NULL, CHANGE endDate endDate DATETIME NOT NULL');
    }
}
