<?php

namespace MatchBot\Application\Messenger;

use MatchBot\Application\Assertion;
use Symfony\Component\Messenger\Bridge\AmazonSqs\MessageDeduplicationAwareInterface;
use Symfony\Component\Messenger\Bridge\AmazonSqs\MessageGroupAwareInterface;

/**
 * Message to tell workers to look for & allocate further match funds if possible.
 * $retroMatchJobUuid is generated by the command that queued all donations, typically
 * one just after the end of each meta-campaign.
 */
class DonationMatchingShouldBeChecked implements MessageDeduplicationAwareInterface, MessageGroupAwareInterface
{
    /**
     * @param array<string> $donationUuids
     */
    protected function __construct(
        public array $donationUuids,
        public string $retroMatchJobUuid,
        public bool $areFinalDonations, // Implies responsibility for reporting the whole command's result.
    ) {
        foreach ($this->donationUuids as $uuid) {
            Assertion::uuid($uuid);
        }
        Assertion::uuid($this->retroMatchJobUuid);
    }

    #[\Override]
    public function getMessageGroupId(): ?string
    {
        return 'donation.rematch.' . $this->retroMatchJobUuid;
    }

    #[\Override]
    public function getMessageDeduplicationId(): ?string
    {
        return 'donation.rematch.' . sha1(implode(',', $this->donationUuids));
    }
}
